import {
  FaAppleAlt,
  FaHeartbeat,
  FaDumbbell,
  FaUtensils,
  FaDrumstickBite,
  FaFire,
  FaStore,
  FaClipboardList,
  FaLeaf,
  FaGift,
  FaTruck,
  FaUsers,
  FaStar,
  FaShieldAlt,
  FaMobileAlt,
  FaMapMarkerAlt,
  FaShoppingBag,
  FaHeart,
  FaChartLine,
  FaTags,
  FaHeadset,
  FaEgg,
  FaGlassWhiskey,
  FaInstagram,
  FaFacebook,
  FaYoutube,
  FaTwitter,
  FaLinkedin,
} from "react-icons/fa";

const iconMap = {
  apple: FaAppleAlt,
  heartbeat: FaHeartbeat,
  dumbbell: FaDumbbell,
  utensils: FaUtensils,
  drumstick: FaDrumstickBite,
  fire: FaFire,
  store: FaStore,
  clipboard: FaClipboardList,
  leaf: FaLeaf,
  gift: FaGift,
  truck: FaTruck,
  users: FaUsers,
  star: FaStar,
  shield: FaShieldAlt,
  mobile: FaMobileAlt,
  map: FaMapMarkerAlt,
  bag: FaShoppingBag,
  heart: FaHeart,
  chart: FaChartLine,
  tags: FaTags,
  headset: FaHeadset,
  egg: FaEgg,
  glass: FaGlassWhiskey,
  instagram: FaInstagram,
  facebook: FaFacebook,
  youtube: FaYoutube,
  twitter: FaTwitter,
  linkedin: FaLinkedin,
};

export default function Icon({ name, className = "" }) {
  const Cmp = iconMap[name];
  if (!Cmp) return null;
  return <Cmp className={className} />;
}
